# Docker Compose for Local Development Services
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  es_data:
  postgres_data:
